### ISSUE TITLE
Not working on OSX

### ISSUE THREAD

**Issue by dimkab** [shivams/zim-zotero-plugin#12]
Hi, I'm new to zim so probably doing something wrong.

I cloned the git repo to ~/.local/share/zim/plugins, and checked that test.py works from  the command line. However, the plugin is not available in Zim itself.

Zotero:5.0.74
zotxt: 5.0.2

**Comment by shivams** [comment]
@dimkab A trivial check. Make sure after cloning, you have a folder `~/.local/share/zim/plugins/zim-zotero-plugin`. 

Further, try running your Zim with `zim -D` from terminal and let me know what debug status it shows regarding this plugin.

**Comment by dimkab** [comment]
Sorry, was using the old version (0.68). With 0.72 it works.
