### ISSUE TITLE
Change format to easykey

### ISSUE THREAD

**Issue by livmion** [shivams/zim-zotero-plugin#5]
Hi all,

First of all, my compliments for the extension.

I just tried to change the `format=bibliography` to `format=easykey`, but then the extension does not give any result. I am no programmer, but I was surprised, since it would be a simple change in the URL and it is working if I call the API manually. Is there any way to accomplish the result I was looking for?

Thank you very much

**Comment by shivams** [comment]
@livmion Thanks for reporting this. I will look into and revert back.
